import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/articles-sidebar"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        <SidebarProvider>
          <AppSidebar />
          <main className="flex-1 flex flex-col overflow-auto">
            <div className="flex items-center gap-2 p-4 border-b">
              <SidebarTrigger />
              <h2 className="font-semibold text-lg">Create Articles</h2>
            </div>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}
